# Save as: scripts/08_build_weekly_slide_images.py
# -*- coding: utf-8 -*-
"""
08 - Build Weekly Slide Images from weekly_scene_package.json

- scene_01.png = weekly_macro_diagram.png
- scene_02~scene_06.png = generated by Gemini image model using Pro-generated image_prompt
- Image logic comes from the same weekly_scene_package used by TTS.
"""

import base64
import json
import os
import shutil
import time
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_WEEKLY_DIR = ROOT_DIR / "output" / "weekly"

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()
IMAGE_MODEL = os.getenv("IMAGE_MODEL", "gemini-3.1-flash-image-preview").strip()
IMAGE_MODEL_FALLBACKS = [
    x.strip()
    for x in os.getenv("IMAGE_MODEL_FALLBACKS", "").split(",")
    if x.strip()
]
FORCE_REBUILD_SLIDES = os.getenv("FORCE_REBUILD_SLIDES", "true").lower() == "true"
GEMINI_TIMEOUT_SECONDS = int(os.getenv("GEMINI_TIMEOUT_SECONDS", "90"))
MAX_IMAGE_RETRIES = int(os.getenv("MAX_IMAGE_RETRIES", "1"))
IMAGE_RETRY_SLEEP_SECONDS = int(os.getenv("IMAGE_RETRY_SLEEP_SECONDS", "10"))

STYLE_APPENDIX = """
請使用 NotebookLM / 白板筆記風格：
米白底、淺灰網格、黑色手繪線條、橘色重點、少量海軍藍。
單頁只講一件事，少字、強視覺、弱邊框。
不要顯示 scene 編號、目前焦點、工程標籤。
不要把旁白逐字稿塞滿畫面。
數字要大，單位要小。
繁體中文。
16:9 靜態圖卡。
""".strip()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def read_json(path: Optional[Path], default: Any = None) -> Any:
    if not path or not path.exists():
        return default if default is not None else {}
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    ensure_dir(path.parent)
    path.write_text(text, encoding="utf-8")


def find_latest_week_dir() -> Path:
    explicit = os.getenv("WEEK_END_DATE", "").strip() or os.getenv("WEEK_DATE", "").strip()
    if explicit:
        p = OUTPUT_WEEKLY_DIR / explicit
        if not p.exists():
            raise FileNotFoundError(f"指定週資料夾不存在：{p}")
        return p
    dirs = [p for p in OUTPUT_WEEKLY_DIR.iterdir() if p.is_dir()]
    if not dirs:
        raise FileNotFoundError("找不到 output/weekly 下的週資料夾")
    dirs.sort(key=lambda p: p.name, reverse=True)
    return dirs[0]


def first_existing(paths: List[Path]) -> Optional[Path]:
    for p in paths:
        if p.exists():
            return p
    return None


def find_diagram(week_dir: Path) -> Optional[Path]:
    return first_existing([
        week_dir / "weekly_macro_diagram.png",
        week_dir / "final" / "weekly_macro_diagram.png",
        week_dir / "data" / "weekly_macro_diagram.png",
        week_dir / "images" / "weekly_macro_diagram.png",
    ])


def encode_image(path: Path) -> Optional[Dict[str, Any]]:
    if not path or not path.exists():
        return None
    suffix = path.suffix.lower()
    mime = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
    }.get(suffix)
    if not mime:
        return None
    return {
        "inlineData": {
            "mimeType": mime,
            "data": base64.b64encode(path.read_bytes()).decode("utf-8")
        }
    }


def build_prompt(scene: Dict[str, Any]) -> str:
    base_prompt = str(scene.get("image_prompt") or "").strip()
    if not base_prompt:
        base_prompt = f"""
請根據此 scene 的敘事規劃產生一張圖卡：
scene_title: {scene.get("scene_title","")}
scene_purpose: {scene.get("scene_purpose","")}
narrative_focus: {scene.get("narrative_focus","")}
visual_direction: {scene.get("visual_direction","")}
on_screen_text: {json.dumps(scene.get("on_screen_text",{}), ensure_ascii=False)}
"""
    return f"{base_prompt}\n\n{STYLE_APPENDIX}".strip()


def call_image_model(prompt: str, reference_images: List[Path]) -> bytes:
    if not GEMINI_API_KEY:
        raise RuntimeError("GEMINI_API_KEY is missing")

    models = [IMAGE_MODEL] + [m for m in IMAGE_MODEL_FALLBACKS if m != IMAGE_MODEL]
    ref_parts = []
    for p in reference_images:
        part = encode_image(p)
        if part:
            ref_parts.append(part)

    last_error = ""
    for model in models:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={GEMINI_API_KEY}"
        payload = {
            "contents": [{"role": "user", "parts": [{"text": prompt}] + ref_parts}],
            "generationConfig": {"temperature": 0.55}
        }
        data = json.dumps(payload).encode("utf-8")

        for attempt in range(1, MAX_IMAGE_RETRIES + 1):
            print(f"[INFO] call image model={model}, attempt={attempt}/{MAX_IMAGE_RETRIES}")
            req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"}, method="POST")
            try:
                with urllib.request.urlopen(req, timeout=GEMINI_TIMEOUT_SECONDS) as resp:
                    raw = resp.read()
                res = json.loads(raw.decode("utf-8"))
                for cand in res.get("candidates", []) or []:
                    for part in (cand.get("content", {}) or {}).get("parts", []) or []:
                        inline = part.get("inlineData") or part.get("inline_data")
                        if inline and inline.get("data"):
                            return base64.b64decode(inline["data"])
                last_error = f"{model} returned no image data"
                print(f"[WARN] {last_error}")
            except urllib.error.HTTPError as exc:
                detail = exc.read().decode("utf-8", errors="ignore")
                last_error = f"{model} HTTP {exc.code}: {detail[:500]}"
                print(f"[WARN] {last_error}")
            except Exception as exc:
                last_error = f"{model}: {exc}"
                print(f"[WARN] {last_error}")
            if attempt < MAX_IMAGE_RETRIES:
                time.sleep(IMAGE_RETRY_SLEEP_SECONDS)

    raise RuntimeError(f"All image model calls failed. Last error: {last_error}")


def fallback_slide(output_path: Path, diagram_path: Optional[Path], reason: str) -> None:
    if output_path.exists():
        print(f"[WARN] keep existing slide {output_path.name}; reason={reason}")
        return
    if diagram_path and diagram_path.exists():
        shutil.copy2(diagram_path, output_path)
        print(f"[WARN] fallback to diagram for {output_path.name}; reason={reason}")
        return
    raise RuntimeError(f"Cannot create fallback slide for {output_path.name}: {reason}")


def main() -> None:
    week_dir = find_latest_week_dir()
    slides_dir = week_dir / "slides"
    prompts_dir = slides_dir / "prompts"
    ensure_dir(slides_dir)
    ensure_dir(prompts_dir)

    package_path = first_existing([
        week_dir / "weekly_scene_package.json",
        week_dir / "narration" / "weekly_scene_package.json",
    ])
    pkg = read_json(package_path, {})
    scenes = pkg.get("scenes", [])
    if not isinstance(scenes, list) or not scenes:
        raise RuntimeError("找不到 weekly_scene_package.json 或 scenes 為空，請先跑 05_generate_weekly_scene_package.py")

    diagram_path = find_diagram(week_dir)
    records = []

    for scene in scenes:
        sid = str(scene.get("scene_id", "")).strip()
        if not sid:
            continue
        out_path = slides_dir / f"{sid}.png"

        if sid == "scene_01":
            if FORCE_REBUILD_SLIDES or not out_path.exists():
                if not diagram_path:
                    raise RuntimeError("scene_01 需要 weekly_macro_diagram.png")
                shutil.copy2(diagram_path, out_path)
                print(f"[OK] scene_01 copied from {diagram_path}")
            records.append({"scene_id": sid, "path": str(out_path), "mode": "copy_diagram"})
            continue

        prompt = build_prompt(scene)
        prompt_path = prompts_dir / f"{sid}_image_prompt.txt"
        write_text(prompt_path, prompt)

        ok = True
        if FORCE_REBUILD_SLIDES or not out_path.exists():
            try:
                image_bytes = call_image_model(prompt, [diagram_path] if diagram_path else [])
                out_path.write_bytes(image_bytes)
                print(f"[OK] wrote {out_path}")
            except Exception as exc:
                ok = False
                fallback_slide(out_path, diagram_path, str(exc))

        records.append({
            "scene_id": sid,
            "path": str(out_path),
            "prompt": str(prompt_path),
            "generated_ok": ok,
            "mode": "image_from_scene_package"
        })

    manifest = {
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "week_dir": str(week_dir),
        "image_model": IMAGE_MODEL,
        "records": records
    }
    (slides_dir / "slides_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    (week_dir / "weekly_slide_images_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[DONE] slides ready: {slides_dir}")


if __name__ == "__main__":
    main()
