#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
94 Test Generate Video Narration Script

Purpose:
- Read weekly_forest_summary.json generated by Step 91.
- Convert narration_outline + video_visual_scenes into a text narration script.
- Do NOT generate TTS audio yet.
- Output markdown and JSON for review before TTS.

Input:
- output/weekly/YYYY-MM-DD/weekly_forest_summary.json

Output:
- output/weekly/YYYY-MM-DD/video_narration_script.md
- output/weekly/YYYY-MM-DD/video_narration_script.json
"""

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List


ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_WEEKLY_DIR = ROOT_DIR / "output" / "weekly"


def find_latest_week_dir() -> Path:
    week_dirs = [p for p in OUTPUT_WEEKLY_DIR.iterdir() if p.is_dir()]
    if not week_dirs:
        raise FileNotFoundError("No weekly output folder found under output/weekly/")
    week_dirs.sort(key=lambda p: p.name, reverse=True)
    return week_dirs[0]


def load_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)


def save_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def save_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def normalize_scene_map(summary: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    scenes = summary.get("video_visual_scenes") or []
    result: Dict[str, Dict[str, Any]] = {}

    if not isinstance(scenes, list):
        return result

    for scene in scenes:
        if not isinstance(scene, dict):
            continue
        scene_id = str(scene.get("scene_id", "")).strip()
        if scene_id:
            result[scene_id] = scene

    return result


def build_spoken_text(scene: Dict[str, Any], narration: Dict[str, Any], idx: int) -> str:
    scene_title = str(scene.get("screen_title") or f"Scene {idx}").strip()
    single_message = str(scene.get("single_message") or "").strip()
    key_points = narration.get("key_points") if isinstance(narration.get("key_points"), list) else []
    evidence = narration.get("evidence_to_mention") if isinstance(narration.get("evidence_to_mention"), list) else []

    sentences: List[str] = []

    if idx == 1:
        if single_message:
            sentences.append(f"這一週市場的主線，可以先用一句話說明：{single_message}")
        else:
            sentences.append("這一週市場的主線，不再是單一方向的總經傳導，而是多個力量同時拉扯。")
    else:
        sentences.append(f"接著看第 {idx} 幕：{scene_title}。")

    for point in key_points[:4]:
        point_text = str(point).strip()
        if point_text:
            sentences.append(point_text)

    if evidence:
        ev = "、".join(str(x).strip() for x in evidence[:3] if str(x).strip())
        if ev:
            sentences.append(f"這裡可以對照的證據是：{ev}。")

    return " ".join(sentences).strip()


def build_narration(summary: Dict[str, Any]) -> Dict[str, Any]:
    forest = summary.get("forest_summary") or {}
    scenes = normalize_scene_map(summary)
    outlines = summary.get("narration_outline") or []

    if not isinstance(outlines, list) or not outlines:
        raise ValueError("weekly_forest_summary.json does not contain usable narration_outline.")

    segments: List[Dict[str, Any]] = []

    for idx, narration in enumerate(outlines, start=1):
        if not isinstance(narration, dict):
            continue

        scene_id = str(narration.get("scene_id") or f"scene_{idx:02d}").strip()
        scene = scenes.get(scene_id, {})
        spoken_text = build_spoken_text(scene, narration, idx)

        segments.append({
            "segment_id": f"narration_segment_{idx:02d}",
            "scene_id": scene_id,
            "screen_title": scene.get("screen_title", ""),
            "single_message": scene.get("single_message", ""),
            "voiceover_goal": narration.get("voiceover_goal", ""),
            "spoken_text": spoken_text,
            "evidence_to_mention": narration.get("evidence_to_mention", []),
            "avoid_saying": narration.get("avoid_saying", []),
            "estimated_seconds": max(20, min(50, round(len(spoken_text) / 5.2))),
        })

    return {
        "meta": {
            "source": "weekly_forest_summary.json",
            "purpose": "text narration review before TTS",
            "segment_count": len(segments),
        },
        "title": forest.get("weekly_main_theme", "本週總經週報旁白稿"),
        "opening": forest.get("one_sentence_verdict", ""),
        "segments": segments,
    }


def build_markdown(data: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append(f"# 影片旁白測試稿｜{data.get('title', '')}")
    lines.append("")

    if data.get("opening"):
        lines.append("## 開場主軸")
        lines.append("")
        lines.append(str(data.get("opening")))
        lines.append("")

    for seg in data.get("segments", []):
        lines.append(f"## {seg.get('scene_id', '')}｜{seg.get('screen_title', '')}")
        lines.append("")
        lines.append(f"**畫面訊息：** {seg.get('single_message', '')}")
        lines.append("")
        lines.append("**旁白稿：**")
        lines.append("")
        lines.append(str(seg.get("spoken_text", "")))
        lines.append("")

        if seg.get("evidence_to_mention"):
            lines.append(f"**可提及證據：** {'、'.join(map(str, seg.get('evidence_to_mention', [])))}")
            lines.append("")

        if seg.get("avoid_saying"):
            lines.append(f"**避免說法：** {'、'.join(map(str, seg.get('avoid_saying', [])))}")
            lines.append("")

        lines.append(f"**預估秒數：** {seg.get('estimated_seconds', '')} 秒")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--week-dir", type=str, default="")
    args = parser.parse_args()

    if args.week_dir:
        week_dir = Path(args.week_dir)
        if not week_dir.exists() and not week_dir.is_absolute():
            candidate = OUTPUT_WEEKLY_DIR / args.week_dir
            if candidate.exists():
                week_dir = candidate
    else:
        week_dir = find_latest_week_dir()

    summary_path = week_dir / "weekly_forest_summary.json"
    summary = load_json(summary_path, {})
    if not summary:
        raise FileNotFoundError(f"Missing or empty weekly_forest_summary.json: {summary_path}")

    data = build_narration(summary)
    md = build_markdown(data)

    json_path = week_dir / "video_narration_script.json"
    md_path = week_dir / "video_narration_script.md"

    save_json(json_path, data)
    save_text(md_path, md)

    print(f"[OK] Created {json_path}")
    print(f"[OK] Created {md_path}")


if __name__ == "__main__":
    main()
