#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
94 Test Generate Video Dialogue Script - Image Grounded Scene Sync v3

Purpose:
- Read weekly_forest_summary.json generated by Step 91.
- Read scene images generated by Step 92.
- Send scene images + scene_control_list + scene_dialogue_context to Gemini.
- Generate formal Tom / Miranda dialogue script for TTS and speaker-label overlay.
- Do NOT generate audio.

Input:
- output/weekly/YYYY-MM-DD/weekly_forest_summary.json
- output/weekly/YYYY-MM-DD/visual_sequence_images/scene_01.png ... scene_N.png

Output:
- output/weekly/YYYY-MM-DD/video_dialogue_script.json
- output/weekly/YYYY-MM-DD/video_dialogue_script.md

Required env:
- GEMINI_API_KEY

Optional env:
- GEMINI_DIALOGUE_MODEL, default: gemini-3.5-pro
- DIALOGUE_TEMPERATURE, default: 0.55
- USE_IMAGE_INPUT_FOR_DIALOGUE, default: true
"""

import argparse
import base64
import json
import mimetypes
import os
import re
import socket
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional


ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_WEEKLY_DIR = ROOT_DIR / "output" / "weekly"
DEFAULT_DIALOGUE_MODEL = "gemini-3.5-pro"


SYSTEM_PROMPT = """
你是專業機構級總經影片編劇與台詞設計師，負責把 Step 91 已經分析好的總經 Facts、Step 92 產出的 scene 圖片，轉譯成 Tom（主持人）與 Miranda（首席總經策略師）可直接進 TTS 的正式雙人逐句對談稿。

一、角色定位
- Tom（主持人）：代表螢幕前具備基礎財經知識的觀眾。他負責看著圖表，拿「過去 2～4 週市場既定印象」對比「本週圖表或數據呈現的反常異象」，問出自然、清楚、尖銳但不破梗的問題。
- Miranda（首席總經策略師）：宏觀解題者。她負責指著畫面，用新聞事件、政策訊號與市場數據拆解因果，不乾念資料，不用數據解釋數據，而是說明哪條新聞線改變了預期、哪些因子正在抵銷。

二、事實與圖像邊界
1. 畫面少字，語音深講：scene 圖片只是視覺錨點；正式台詞必須把 scene_dialogue_context 裡的 prior_market_impression、this_week_catalyst、data_validation、causal_interpretation、offset_or_risk、tom_question_angle、miranda_talk_track 轉成自然對談。
2. 實際圖片優先對齊：每一幕必須優先描述該 scene 圖片中「實際可見」的視覺隱喻、標籤與數字，不可沿用 metadata 裡不存在於圖片上的舊視覺描述。
3. Metadata 為準：若圖片文字與 weekly_forest_summary 的事實資料不一致，以 weekly_forest_summary 為準；但視覺物件描述必須以實際圖片為準。
4. 不能憑圖編新聞：圖片只用於畫面對齊，新聞與因果素材必須來自 supporting_context，特別是 scene_dialogue_context、macro_storyline、transmission_diagnosis、common_judgment_funnel、evidence。
5. 完整因果鏈：Miranda 的回答必須包含「前因慣性 → 本週催化事件 → 市場數據驗證 / 抵銷 → 總經定價機制 → 下一幕伏筆」。
6. 伏筆而不暴雷：Miranda 可以在結尾銜接下一幕，但不能提前把下一幕完整分析講完。

三、視覺錨點使用原則
1. 圖片是觀眾理解本幕主題的入口，不是完整的總經模型。台詞應先用一句話指出畫面中最醒目的視覺元素，再用 supporting_context 補上真正的因果解釋。
2. 不要硬套固定隱喻。若圖片中沒有明確呈現某種物件或結構，不要自行套用天平、拔河、漢堡、溺水、折線等既有說法。
3. 只描述實際看得到的元素：可見的物件、位置關係、標籤、數字、方向、顏色或強弱對比。看不清楚或不存在的元素，不要編入台詞。
4. 視覺描述要保持簡短，重點放在「這張圖讓觀眾先抓到什麼粗略概念」。真正的總經邏輯要回到 scene_dialogue_context、macro_storyline、transmission_diagnosis、common_judgment_funnel 和 evidence。
5. 若圖片呈現對立、壓力、支撐、分化、轉折、路徑、障礙、警示、觀察等抽象關係，Miranda 可以用這些關係銜接總經解釋；但不能把圖片解讀成不存在的具體道具或模型。
6. 如果圖片只是概念插圖，沒有明確數據或結構，Tom 只需用一句自然觀察帶入，例如「這張圖像是在提醒我們，本週市場不是單一路徑，而是幾個力量同時作用。」不要過度逐物件解釋。

四、語氣與合規邊界
1. 口吻控制：台灣專業財經節目口語，清楚、有節奏、有洞察，但避免過度戲劇化或網路化詞彙。
2. 投資建議邊界：本節目只做總經事件、資產反應與市場定價邏輯的說明，不提供買賣建議、進出場判斷、報酬承諾或單一方向押注。避免使用「應該買/賣」、「可以進場」、「不要押注」、「多看少做」等操作式語句；若需要收尾，改用「後續仍需觀察」、「持續追蹤關鍵訊號」、「等待更多數據驗證」等中性表述。
3. 主持人口吻：Tom 可以口語化、自然提問，但要維持內斂、平鋪直敘與專業節制；可以表達「困惑、反直覺、矛盾」，但不要用過度驚嚇、煽動、網路化或投資建議式語氣。
4. 硬性避免詞：不得使用「精神分裂」、「核彈級」、「尚方寶劍」、「崩盤」、「全面失守」、「躺平任人捶打」、「免死金牌」、「哀鴻遍野」等會破壞機構級節目質感的詞。

五、對話節奏與結構
1. 每個 scene 優先產生 3～4 個 speaker_turns，避免只用 Tom 一問、Miranda 一答就結束。
2. Tom 的單次發言不能過短。除非是最後的簡短回應，Tom 每次 spoken_text 建議至少 25 個中文字，讓 TTS 與畫面字卡有足夠停留時間。
3. 除最後收尾幕外，單一 speaker_turn 的 estimated_seconds 不宜超過 35 秒。
4. 如果 Miranda 分析超過 35 秒，必須拆成「Miranda 先解釋 → Tom 承接 / 追問 → Miranda 補充」的節奏，讓影片頭像與字幕有自然呼吸。
5. 最後一幕必須由 Tom 收尾，形成節目完結感。收尾可以感謝 Miranda、提醒觀眾持續追蹤後續數據與關鍵訊號，並自然說「我們下週見」；避免投資建議式語氣。
6. news_reference 必須跨幕一致。若某一幕使用前一幕的新聞因果作為解釋，例如用「房市數據疲軟」解釋黃金避險需求，該 turn 的 news_reference 必須補上該新聞線索。
7. 嚴格輸出合法 JSON，不要 Markdown，不要多餘文字。
"""



USER_PROMPT_TEMPLATE = """
請根據下方資料，產生正式 video_dialogue_script.json。

本次任務：
- 嚴格依照 scene_output_control 的場景數量與順序，為每一個 scene 產生一組正式雙人對談台詞。
- 如果 actual_scene_image_files 不為空，scene_dialogues 必須與實際圖片 scene 清單完全一致，不得多、不得少、不得漏。
- 若沒有圖片，則以 scene_control_list / video_visual_scenes 為主控清單。
- 必須使用 supporting_context 與 scene_dialogue_context 作為事實來源，不可只使用 video_visual_scenes。
- 請遵守 SYSTEM_PROMPT 中的角色定位、事實邊界、圖文對齊、動態解圖、語氣合規、對話節奏與 news_reference 規則。
- subtitle_text 必須是精簡字幕，不超過 25 個中文字；不要直接複製完整 spoken_text。
- visual_reference 必須指出本 turn 對應的圖上實際可見物件或 scene_id。
- news_reference 必須列出本 turn 用到的新聞 / 政策 / 數據線索；沒有就填空陣列。

輸出 JSON 結構：
{
  "meta": {
    "source": "scene_images + scene_control_list + scene_dialogue_context + supporting_context",
    "purpose": "image-grounded Tom / Miranda formal dialogue script before TTS",
    "week_range": "",
    "scene_count": 0,
    "used_image_input": true,
    "dialogue_model_note": ""
  },
  "title": "",
  "opening_hook": "",
  "speaker_profiles": {
    "Tom": {
      "display_name": "Tom",
      "role_label": "主持人",
      "voice_role": "male_host",
      "screen_position": "lower_left"
    },
    "Miranda": {
      "display_name": "Miranda",
      "role_label": "總經策略師",
      "voice_role": "female_strategist",
      "screen_position": "lower_left"
    }
  },
  "scene_dialogues": [
    {
      "scene_id": "scene_01",
      "scene_type": "",
      "screen_title": "",
      "single_message": "",
      "visual_anchor": {
        "visible_elements_used": [],
        "must_align_with": [],
        "do_not_expand": []
      },
      "source_material_used": [],
      "speaker_turns": [
        {
          "turn_id": "scene_01_turn_01",
          "speaker": "Tom",
          "display_name": "Tom",
          "role_label": "主持人",
          "spoken_text": "",
          "subtitle_text": "",
          "speaker_label_text": "Tom｜主持人",
          "estimated_seconds": 0,
          "news_reference": [],
          "visual_reference": ""
        },
        {
          "turn_id": "scene_01_turn_02",
          "speaker": "Miranda",
          "display_name": "Miranda",
          "role_label": "總經策略師",
          "spoken_text": "",
          "subtitle_text": "",
          "speaker_label_text": "Miranda｜總經策略師",
          "estimated_seconds": 0,
          "news_reference": [],
          "visual_reference": ""
        }
      ],
      "scene_summary": "",
      "avoid_saying": []
    }
  ],
  "tts_plan": {
    "voice_strategy": "Tom male host, Miranda female strategist",
    "needs_tts": true,
    "needs_speaker_label_overlay": true,
    "subtitle_mode": "turn_by_turn"
  },
  "quality_checks": {
    "scene_alignment_note": "",
    "image_grounding_note": "",
    "dialogue_naturalness_note": "",
    "news_driven_logic_note": "",
    "continuity_note": "",
    "risk_control_note": ""
  }
}

以下是資料：
{scene_payload_json}
"""



def parse_bool(value: str, default: bool = True) -> bool:
    if value is None:
        return default
    text = str(value).strip().lower()
    if text in {"1", "true", "yes", "y", "on"}:
        return True
    if text in {"0", "false", "no", "n", "off"}:
        return False
    return default


def as_list(value: Any) -> List[Any]:
    if isinstance(value, list):
        return value
    if value in (None, ""):
        return []
    return [value]


def find_latest_week_dir() -> Path:
    week_dirs = [p for p in OUTPUT_WEEKLY_DIR.iterdir() if p.is_dir()]
    if not week_dirs:
        raise FileNotFoundError("No weekly output folder found under output/weekly/")
    week_dirs.sort(key=lambda p: p.name, reverse=True)
    return week_dirs[0]


def resolve_week_dir(week_dir_arg: str) -> Path:
    if week_dir_arg:
        week_dir = Path(week_dir_arg)
        if week_dir.exists():
            return week_dir
        candidate = OUTPUT_WEEKLY_DIR / week_dir_arg
        if candidate.exists():
            return candidate
        raise FileNotFoundError(f"Week folder not found: {week_dir_arg}")
    return find_latest_week_dir()


def load_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)


def save_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def save_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def find_scene_image(week_dir: Path, scene_id: str) -> Optional[Path]:
    candidates = []
    image_dir = week_dir / "visual_sequence_images"
    for ext in [".png", ".jpg", ".jpeg", ".webp"]:
        candidates.append(image_dir / f"{scene_id}{ext}")
        candidates.append(week_dir / f"{scene_id}{ext}")

    if image_dir.exists():
        for p in image_dir.iterdir():
            if p.is_file() and p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"}:
                if p.stem.lower() == scene_id.lower():
                    candidates.append(p)

    for path in candidates:
        if path.exists() and path.is_file():
            return path
    return None


def encode_image_part(path: Path) -> Dict[str, Any]:
    mime_type, _ = mimetypes.guess_type(str(path))
    if not mime_type:
        mime_type = "image/png"
    data = base64.b64encode(path.read_bytes()).decode("ascii")
    return {
        "inline_data": {
            "mime_type": mime_type,
            "data": data,
        }
    }


def get_scene_output_control(summary: Dict[str, Any], week_dir: Path, use_image_input: bool) -> List[Dict[str, Any]]:
    """
    Output control priority:
    1. actual scene images if image input is effective
    2. scene_control_list from Step 91
    3. video_visual_scenes from Step 91
    """
    visual_by_id = {
        str(item.get("scene_id", "")): item
        for item in as_list(summary.get("video_visual_scenes"))
        if isinstance(item, dict)
    }
    control_by_id = {
        str(item.get("scene_id", "")): item
        for item in as_list(summary.get("scene_control_list"))
        if isinstance(item, dict)
    }

    if use_image_input:
        image_dir = week_dir / "visual_sequence_images"
        image_scene_ids: List[str] = []
        if image_dir.exists():
            image_files = sorted(
                p for p in image_dir.iterdir()
                if p.is_file() and p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"}
            )
            image_scene_ids = [p.stem for p in image_files if p.stem.startswith("scene_")]

        if image_scene_ids:
            output = []
            for idx, scene_id in enumerate(image_scene_ids, start=1):
                v = visual_by_id.get(scene_id, {})
                c = control_by_id.get(scene_id, {})
                output.append({
                    "scene_id": scene_id,
                    "scene_type": v.get("scene_type") or c.get("scene_type", ""),
                    "screen_title": v.get("screen_title") or c.get("screen_title", ""),
                    "single_message": v.get("single_message") or c.get("single_message", ""),
                    "image_file": f"visual_sequence_images/{scene_id}.png",
                    "source": "actual_image_files",
                })
            return output

    control = as_list(summary.get("scene_control_list"))
    if control:
        output = []
        for item in control:
            if not isinstance(item, dict):
                continue
            scene_id = str(item.get("scene_id", ""))
            v = visual_by_id.get(scene_id, {})
            output.append({
                "scene_id": scene_id,
                "scene_type": v.get("scene_type") or item.get("scene_type", ""),
                "screen_title": v.get("screen_title") or item.get("screen_title", ""),
                "single_message": v.get("single_message") or item.get("single_message", ""),
                "image_file": "",
                "source": "scene_control_list",
            })
        return output

    scenes = as_list(summary.get("video_visual_scenes"))
    return [
        {
            "scene_id": str(scene.get("scene_id", f"scene_{idx:02d}")),
            "scene_type": scene.get("scene_type", ""),
            "screen_title": scene.get("screen_title", ""),
            "single_message": scene.get("single_message", ""),
            "image_file": "",
            "source": "video_visual_scenes",
        }
        for idx, scene in enumerate(scenes, start=1)
        if isinstance(scene, dict)
    ]


def build_compact_scenes(summary: Dict[str, Any], week_dir: Path, use_image_input: bool) -> List[Dict[str, Any]]:
    scenes = as_list(summary.get("video_visual_scenes"))
    dialogue_context = {
        str(item.get("scene_id", "")): item
        for item in as_list(summary.get("scene_dialogue_context"))
        if isinstance(item, dict)
    }
    narration = {
        str(item.get("scene_id", "")): item
        for item in as_list(summary.get("narration_outline"))
        if isinstance(item, dict)
    }

    compact: List[Dict[str, Any]] = []
    for scene in scenes:
        if not isinstance(scene, dict):
            continue
        scene_id = str(scene.get("scene_id", ""))
        image_path = find_scene_image(week_dir, scene_id)
        compact.append({
            "scene_id": scene_id,
            "scene_type": scene.get("scene_type", ""),
            "screen_title": scene.get("screen_title", ""),
            "single_message": scene.get("single_message", ""),
            "on_screen_labels": scene.get("on_screen_labels", []),
            "must_show_numbers": scene.get("must_show_numbers", []),
            "visual_metaphor": scene.get("visual_metaphor", ""),
            "image_file": str(image_path.relative_to(week_dir)) if image_path else "",
            "image_available": bool(image_path and use_image_input),
            "scene_dialogue_context": dialogue_context.get(scene_id, {}),
            "narration_outline": narration.get(scene_id, {}),
        })
    return compact


def build_scene_payload(summary: Dict[str, Any], week_dir: Path, use_image_input: bool) -> Dict[str, Any]:
    compact_scenes = build_compact_scenes(summary, week_dir, use_image_input)
    scene_output_control = get_scene_output_control(summary, week_dir, use_image_input)

    return {
        "week_range": (summary.get("meta") or {}).get("week_range", ""),
        "title_hint": (summary.get("video_planning") or {}).get("suggested_video_title", ""),
        "opening_hook_hint": (summary.get("video_planning") or {}).get("opening_hook", ""),
        "used_image_input_requested": use_image_input,
        "scene_output_control": scene_output_control,
        "scene_control_list": summary.get("scene_control_list", []),
        "actual_scene_image_files": [
            item.get("image_file", "")
            for item in scene_output_control
            if item.get("source") == "actual_image_files"
        ],
        "video_visual_scenes": compact_scenes,
        "supporting_context": {
            "forest_summary": summary.get("forest_summary", {}),
            "common_judgment_funnel": summary.get("common_judgment_funnel", {}),
            "macro_storyline": summary.get("macro_storyline", {}),
            "macro_variables": summary.get("macro_variables", {}),
            "transmission_diagnosis": summary.get("transmission_diagnosis", {}),
            "scene_dialogue_context": summary.get("scene_dialogue_context", []),
            "narration_outline": summary.get("narration_outline", []),
            "evidence": summary.get("evidence", {}),
            "video_planning": {
                "video_thesis": (summary.get("video_planning") or {}).get("video_thesis", ""),
                "opening_hook": (summary.get("video_planning") or {}).get("opening_hook", ""),
                "next_week_questions": (summary.get("video_planning") or {}).get("next_week_questions", []),
            },
        },
    }


def build_content_parts(summary: Dict[str, Any], week_dir: Path, use_image_input: bool) -> List[Dict[str, Any]]:
    payload = build_scene_payload(summary, week_dir, use_image_input)
    prompt = USER_PROMPT_TEMPLATE.replace(
        "{scene_payload_json}",
        json.dumps(payload, ensure_ascii=False, indent=2),
    )

    parts: List[Dict[str, Any]] = [{"text": prompt}]

    if not use_image_input:
        return parts

    for scene in as_list(summary.get("video_visual_scenes")):
        if not isinstance(scene, dict):
            continue
        scene_id = str(scene.get("scene_id", ""))
        image_path = find_scene_image(week_dir, scene_id)
        if not image_path:
            continue
        parts.append({
            "text": f"以下圖片對應 {scene_id}。請用它理解該幕畫面元素；若圖片文字與 weekly_forest_summary 不一致，以 weekly_forest_summary 為準。"
        })
        parts.append(encode_image_part(image_path))

    return parts


def extract_json(text: str) -> Dict[str, Any]:
    text = text.strip()
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("Gemini response does not contain a JSON object.")
    return json.loads(text[start:end + 1], strict=False)


def call_gemini_json(parts: List[Dict[str, Any]], model: str, api_key: str, temperature: float) -> Dict[str, Any]:
    endpoint = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        + urllib.parse.quote(model)
        + ":generateContent?key="
        + urllib.parse.quote(api_key)
    )
    payload = {
        "systemInstruction": {"parts": [{"text": SYSTEM_PROMPT}]},
        "contents": [{"role": "user", "parts": parts}],
        "generationConfig": {
            "temperature": temperature,
            "topP": 0.9,
            "responseMimeType": "application/json",
        },
    }
    request = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=360) as response:
            raw = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Gemini dialogue HTTPError {exc.code}: {detail}") from exc
    except (urllib.error.URLError, TimeoutError, socket.timeout) as exc:
        raise RuntimeError(f"Gemini dialogue request failed or timed out: {exc}") from exc

    result = json.loads(raw)
    candidates = result.get("candidates") or []
    if not candidates:
        raise RuntimeError(f"Gemini returned no candidates. Preview: {raw[:1200]}")
    parts_out = (candidates[0].get("content") or {}).get("parts") or []
    text = "".join(str(part.get("text", "")) for part in parts_out)
    if not text.strip():
        raise RuntimeError(f"Gemini returned empty text. Preview: {raw[:1200]}")
    return extract_json(text)


def estimate_seconds(text: str) -> int:
    return max(3, min(50, round(len(text or "") / 4.7)))


def short_subtitle(text: str, max_len: int = 25) -> str:
    text = (text or "").strip().replace("\n", " ")
    if len(text) <= max_len:
        return text
    return text[:max_len].rstrip("，。；、 ") + "…"






def sanitize_tone_phrases(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Post-process only hard-banned tone phrases that damage institutional program quality.
    Do not use this function to rewrite ordinary spoken style; general tone is controlled by SYSTEM_PROMPT.
    """
    replacements = {
        "精神分裂的一週": "結構性拉鋸的一週",
        "精神分裂": "結構性拉鋸",
        "核彈級的利空": "非常沉重的利空",
        "核彈級利空": "非常沉重的利空",
        "核彈級": "高權重",
        "躺平任人捶打": "承受明顯貶值壓力",
        "躺平承受重壓": "承受明顯貶值壓力",
        "躺平": "承受壓力",
        "崩盤": "大幅修正",
        "全面失守": "壓力明顯升高",
        "哀鴻遍野": "壓力明顯升高",
        "免死金牌": "政策安全墊",
        "尚方寶劍": "政策工具",
    }

    hard_avoid_terms = [
        "精神分裂",
        "核彈級",
        "躺平任人捶打",
        "崩盤",
        "全面失守",
        "哀鴻遍野",
        "免死金牌",
        "尚方寶劍",
    ]

    changed_turns: List[str] = []

    for scene in data.get("scene_dialogues", []) or []:
        if not isinstance(scene, dict):
            continue

        for field in ["scene_summary", "single_message"]:
            if isinstance(scene.get(field), str):
                original = scene[field]
                updated = original
                for old, new in replacements.items():
                    updated = updated.replace(old, new)
                if updated != original:
                    scene[field] = updated

        avoid = scene.get("avoid_saying")
        if isinstance(avoid, list):
            for term in hard_avoid_terms:
                if term not in avoid:
                    avoid.append(term)
            scene["avoid_saying"] = avoid

        for turn in scene.get("speaker_turns", []) or []:
            if not isinstance(turn, dict):
                continue

            changed = False
            for field in ["spoken_text", "subtitle_text", "visual_reference"]:
                if not isinstance(turn.get(field), str):
                    continue
                original = turn[field]
                updated = original
                for old, new in replacements.items():
                    updated = updated.replace(old, new)
                if updated != original:
                    turn[field] = updated
                    changed = True

            if changed:
                changed_turns.append(str(turn.get("turn_id", "")))

    if changed_turns:
        qc = data.setdefault("quality_checks", {})
        prev = str(qc.get("risk_control_note", ""))
        qc["risk_control_note"] = (
            (prev + " " if prev else "")
            + f"Sanitized hard-banned tone phrases in turns: {changed_turns}."
        )

    return data


def ensure_minimum_tom_turns(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Add a quality note when Tom turns are too short.
    We do not rewrite generated content here, but we surface the issue clearly.
    """
    short_turns: List[str] = []
    for scene in data.get("scene_dialogues", []) or []:
        if not isinstance(scene, dict):
            continue
        scene_id = str(scene.get("scene_id", ""))
        for turn in scene.get("speaker_turns", []) or []:
            if not isinstance(turn, dict):
                continue
            if turn.get("speaker") != "Tom":
                continue
            spoken = str(turn.get("spoken_text", "")).strip()
            # Allow final closing turn and very short connector questions, but flag very short ones.
            if 0 < len(spoken) < 18:
                short_turns.append(str(turn.get("turn_id") or scene_id))

    if short_turns:
        qc = data.setdefault("quality_checks", {})
        prev = str(qc.get("dialogue_naturalness_note", ""))
        qc["dialogue_naturalness_note"] = (
            (prev + " " if prev else "")
            + f"Tom has very short turns that may create visual flicker in TTS/video: {short_turns}."
        )
    return data


def ensure_final_tom_closing(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Ensure the last scene ends with Tom, so the video has a proper closing rhythm.
    """
    scenes = data.get("scene_dialogues")
    if not isinstance(scenes, list) or not scenes:
        return data

    last_scene = scenes[-1]
    if not isinstance(last_scene, dict):
        return data

    turns = last_scene.setdefault("speaker_turns", [])
    if not isinstance(turns, list):
        turns = []
        last_scene["speaker_turns"] = turns

    if turns and isinstance(turns[-1], dict) and turns[-1].get("speaker") == "Tom":
        return data

    scene_id = str(last_scene.get("scene_id", "scene"))
    turn_idx = len(turns) + 1
    closing_text = (
        "明白了。在這些關鍵訊號明朗之前，市場仍需要保持彈性、持續觀察風險變化。"
        "非常感謝 Miranda 的深度拆解，也謝謝觀眾朋友收看，我們下週見。"
    )

    turns.append({
        "turn_id": f"{scene_id}_turn_{turn_idx:02d}",
        "speaker": "Tom",
        "display_name": "Tom",
        "role_label": "主持人",
        "spoken_text": closing_text,
        "subtitle_text": "感謝收看，保持彈性，我們下週見。",
        "speaker_label_text": "Tom｜主持人",
        "estimated_seconds": estimate_seconds(closing_text),
        "news_reference": [],
        "visual_reference": last_scene.get("scene_id", ""),
    })

    qc = data.setdefault("quality_checks", {})
    prev = str(qc.get("continuity_note", ""))
    qc["continuity_note"] = (prev + " " if prev else "") + "Added final Tom closing turn for proper ending rhythm."
    return data


def enrich_cross_scene_news_references(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Patch common cross-scene causal references so downstream video/news labels do not miss them.
    This is intentionally conservative and only adds obvious references based on spoken_text.
    """
    keyword_refs = [
        (["房市", "成長隱憂"], "房市數據疲軟引發成長降溫擔憂"),
        (["經濟成長隱憂"], "房市數據疲軟引發成長降溫擔憂"),
        (["避險", "黃金"], "經濟成長隱憂支撐黃金避險需求"),
        (["升息", "會議紀錄"], "Fed會議紀錄重啟升息討論"),
        (["美伊", "和平"], "美伊和平協議傳聞"),
    ]

    for scene in data.get("scene_dialogues", []) or []:
        if not isinstance(scene, dict):
            continue
        for turn in scene.get("speaker_turns", []) or []:
            if not isinstance(turn, dict):
                continue
            spoken = str(turn.get("spoken_text", ""))
            refs = turn.get("news_reference")
            if not isinstance(refs, list):
                refs = []
            for keywords, ref in keyword_refs:
                if all(k in spoken for k in keywords) and ref not in refs:
                    refs.append(ref)
            turn["news_reference"] = refs

    return data



def split_sentences_for_turn(text: str) -> List[str]:
    """Split Chinese spoken text into sentence-like chunks while keeping punctuation."""
    cleaned = (text or "").strip()
    if not cleaned:
        return []
    parts = re.split(r"(?<=[。！？?!])", cleaned)
    return [p.strip() for p in parts if p and p.strip()]


def bridge_text_for_scene(scene_type: str, scene_title: str) -> str:
    """Create a short, stable Tom bridge when a Miranda monologue needs to be split."""
    scene_type = str(scene_type or "")
    if scene_type == "inflation_expectation":
        return "所以關鍵不是油價跌了就代表通膨問題結束，而是要分清楚能源端和核心通膨的訊號，對嗎？"
    if scene_type == "rate_expectation":
        return "也就是說，債市真正害怕的不是單一數據，而是政策路徑重新被定價，這點很關鍵。"
    if scene_type == "dollar_index":
        return "所以美元不是沒有支撐，而是上方同時被成長疑慮壓住，這才形成高檔震盪。"
    if scene_type == "asia_fx_gold":
        return "這樣看起來，亞幣和黃金其實不是同一套定價邏輯，分化反而是合理的結果。"
    if scene_type == "next_week_roadmap":
        return "所以下週其實不是猜單一方向，而是要驗證這兩條線索哪一條會被市場確認。"
    return "所以這裡的重點，是把畫面上的市場現象拆成不同驅動因子來看，不能只看單一數字。"


def rebalance_long_speaker_turns(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Prevent 2-turn scenes with very long Miranda monologues.
    If a scene has too few turns and a Miranda turn is too long, split it into:
    Miranda first half -> Tom bridge -> Miranda second half.
    """
    changed_scenes: List[str] = []

    for scene in data.get("scene_dialogues", []) or []:
        if not isinstance(scene, dict):
            continue

        turns = [t for t in as_list(scene.get("speaker_turns")) if isinstance(t, dict)]
        if len(turns) >= 3:
            continue

        new_turns: List[Dict[str, Any]] = []
        changed = False
        scene_id = str(scene.get("scene_id", "scene"))
        scene_type = str(scene.get("scene_type", ""))
        scene_title = str(scene.get("screen_title", ""))

        for turn in turns:
            speaker = str(turn.get("speaker", ""))
            spoken = str(turn.get("spoken_text", "")).strip()
            estimated = int(turn.get("estimated_seconds") or estimate_seconds(spoken))

            if speaker == "Miranda" and estimated > 35:
                sentences = split_sentences_for_turn(spoken)
                if len(sentences) >= 4:
                    midpoint = max(2, len(sentences) // 2)
                    first_text = "".join(sentences[:midpoint]).strip()
                    second_text = "".join(sentences[midpoint:]).strip()

                    first = dict(turn)
                    first["spoken_text"] = first_text
                    first["subtitle_text"] = short_subtitle(str(first.get("subtitle_text") or first_text))
                    first["estimated_seconds"] = estimate_seconds(first_text)

                    bridge_text = bridge_text_for_scene(scene_type, scene_title)
                    bridge = {
                        "turn_id": "",
                        "speaker": "Tom",
                        "display_name": "Tom",
                        "role_label": "主持人",
                        "spoken_text": bridge_text,
                        "subtitle_text": short_subtitle(bridge_text),
                        "speaker_label_text": "Tom｜主持人",
                        "estimated_seconds": max(8, estimate_seconds(bridge_text)),
                        "news_reference": [],
                        "visual_reference": turn.get("visual_reference", scene_id),
                    }

                    second = dict(turn)
                    second["spoken_text"] = second_text
                    second["subtitle_text"] = short_subtitle(second_text)
                    second["estimated_seconds"] = estimate_seconds(second_text)

                    new_turns.extend([first, bridge, second])
                    changed = True
                    continue

            new_turns.append(turn)

        if changed:
            for idx, turn in enumerate(new_turns, start=1):
                speaker = str(turn.get("speaker") or "Miranda")
                role = "主持人" if speaker == "Tom" else "總經策略師"
                spoken = str(turn.get("spoken_text", "")).strip()
                turn["turn_id"] = f"{scene_id}_turn_{idx:02d}"
                turn["speaker"] = speaker
                turn["display_name"] = speaker
                turn["role_label"] = role
                turn["speaker_label_text"] = f"{speaker}｜{role}"
                turn["subtitle_text"] = short_subtitle(str(turn.get("subtitle_text") or spoken))
                turn["estimated_seconds"] = int(turn.get("estimated_seconds") or estimate_seconds(spoken))
                turn.setdefault("news_reference", [])
                turn.setdefault("visual_reference", scene_id)

            scene["speaker_turns"] = new_turns
            changed_scenes.append(scene_id)

    if changed_scenes:
        qc = data.setdefault("quality_checks", {})
        prev = str(qc.get("dialogue_naturalness_note", ""))
        qc["dialogue_naturalness_note"] = (
            (prev + " " if prev else "")
            + f"Rebalanced long Miranda turns in scenes: {changed_scenes}."
        )

    return data


def normalize_dialogue(data: Dict[str, Any], summary: Dict[str, Any], week_dir: Path, used_image_input: bool) -> Dict[str, Any]:
    scene_output_control = get_scene_output_control(summary, week_dir, used_image_input)
    control_ids = [item.get("scene_id", "") for item in scene_output_control if item.get("scene_id")]

    data.setdefault("meta", {})
    data["meta"].setdefault("source", "scene_images + scene_control_list + scene_dialogue_context + supporting_context")
    data["meta"].setdefault("purpose", "image-grounded Tom / Miranda formal dialogue script before TTS")
    data["meta"].setdefault("week_range", (summary.get("meta") or {}).get("week_range", ""))
    data["meta"]["scene_count"] = len(control_ids)
    data["meta"]["used_image_input"] = bool(used_image_input)

    data.setdefault("speaker_profiles", {
        "Tom": {"display_name": "Tom", "role_label": "主持人", "voice_role": "male_host", "screen_position": "lower_left"},
        "Miranda": {"display_name": "Miranda", "role_label": "總經策略師", "voice_role": "female_strategist", "screen_position": "lower_left"},
    })

    existing = data.get("scene_dialogues")
    if not isinstance(existing, list):
        existing = []
    by_id = {
        str(scene.get("scene_id", "")): scene
        for scene in existing
        if isinstance(scene, dict)
    }

    aligned_scenes: List[Dict[str, Any]] = []
    missing: List[str] = []

    for ctrl in scene_output_control:
        scene_id = str(ctrl.get("scene_id", ""))
        scene = dict(by_id.get(scene_id, {}))
        if not scene:
            missing.append(scene_id)
            scene = {
                "scene_id": scene_id,
                "scene_type": ctrl.get("scene_type", ""),
                "screen_title": ctrl.get("screen_title", ""),
                "single_message": ctrl.get("single_message", ""),
                "visual_anchor": {
                    "visible_elements_used": [],
                    "must_align_with": [],
                    "do_not_expand": [],
                },
                "source_material_used": [],
                "speaker_turns": [],
                "scene_summary": "",
                "avoid_saying": [],
            }

        scene["scene_id"] = scene_id
        scene["scene_type"] = scene.get("scene_type") or ctrl.get("scene_type", "")
        scene["screen_title"] = scene.get("screen_title") or ctrl.get("screen_title", "")
        scene["single_message"] = scene.get("single_message") or ctrl.get("single_message", "")

        turns = scene.get("speaker_turns") or []
        if not isinstance(turns, list):
            turns = []

        normalized_turns = []
        for idx, turn in enumerate(turns, start=1):
            if not isinstance(turn, dict):
                continue
            speaker = str(turn.get("speaker") or "Miranda").strip()
            if speaker not in {"Tom", "Miranda"}:
                speaker = "Miranda"
            role = "主持人" if speaker == "Tom" else "總經策略師"
            spoken = str(turn.get("spoken_text", "")).strip()
            turn["speaker"] = speaker
            turn["display_name"] = speaker
            turn["role_label"] = role
            turn["speaker_label_text"] = f"{speaker}｜{role}"
            turn["turn_id"] = turn.get("turn_id") or f"{scene_id}_turn_{idx:02d}"
            turn["subtitle_text"] = short_subtitle(str(turn.get("subtitle_text") or spoken))
            estimated = int(turn.get("estimated_seconds") or estimate_seconds(spoken))
            if speaker == "Tom" and len(spoken) >= 18:
                estimated = max(8, estimated)
            turn["estimated_seconds"] = estimated
            turn.setdefault("news_reference", [])
            turn.setdefault("visual_reference", scene_id)
            normalized_turns.append(turn)

        scene["speaker_turns"] = normalized_turns
        scene.setdefault("visual_anchor", {
            "visible_elements_used": [],
            "must_align_with": [],
            "do_not_expand": [],
        })
        scene.setdefault("source_material_used", [])
        scene.setdefault("avoid_saying", [])
        aligned_scenes.append(scene)

    data["scene_dialogues"] = aligned_scenes

    data.setdefault("tts_plan", {
        "voice_strategy": "Tom male host, Miranda female strategist",
        "needs_tts": True,
        "needs_speaker_label_overlay": True,
        "subtitle_mode": "turn_by_turn",
    })

    qc = data.setdefault("quality_checks", {})
    qc.setdefault("scene_alignment_note", "")
    qc["scene_alignment_note"] = (
        qc["scene_alignment_note"] + " " if qc["scene_alignment_note"] else ""
    ) + f"Aligned scene_dialogues to control ids: {control_ids}."
    if missing:
        qc["scene_alignment_note"] += f" Missing scenes were backfilled as placeholders: {missing}."

    return data


def build_markdown(data: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append(f"# 影片雙人正式旁白稿｜{data.get('title', '')}")
    lines.append("")

    if data.get("opening_hook"):
        lines.append("## Opening Hook")
        lines.append("")
        lines.append(str(data.get("opening_hook", "")))
        lines.append("")

    for scene in data.get("scene_dialogues", []) or []:
        lines.append(f"## {scene.get('scene_id', '')}｜{scene.get('screen_title', '')}")
        lines.append("")

        if scene.get("single_message"):
            lines.append(f"畫面訊息：{scene.get('single_message')}")
            lines.append("")

        if scene.get("visual_anchor"):
            lines.append("### Visual Anchor")
            lines.append("")
            for key, value in (scene.get("visual_anchor") or {}).items():
                lines.append(f"- {key}: {value}")
            lines.append("")

        turns = scene.get("speaker_turns") or []
        for turn in turns:
            speaker = turn.get("speaker", "")
            role = turn.get("role_label", "")
            spoken = turn.get("spoken_text", "")
            subtitle = turn.get("subtitle_text", "")

            lines.append(f"**[{speaker}｜{role}]** {spoken}")
            if subtitle:
                lines.append(f"> 字幕：{subtitle}")
            if turn.get("visual_reference"):
                lines.append(f"> 畫面：{turn.get('visual_reference')}")
            if turn.get("news_reference"):
                lines.append(f"> 素材：{turn.get('news_reference')}")
            lines.append("")

        if scene.get("scene_summary"):
            lines.append(f"小結：{scene.get('scene_summary')}")
            lines.append("")

    return "\n".join(lines).strip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--week-dir", type=str, default="")
    parser.add_argument("--use-image-input", type=str, default="")
    args = parser.parse_args()

    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        raise EnvironmentError("Missing GEMINI_API_KEY.")

    model = os.getenv("GEMINI_DIALOGUE_MODEL", DEFAULT_DIALOGUE_MODEL).strip() or DEFAULT_DIALOGUE_MODEL
    try:
        temperature = float(os.getenv("DIALOGUE_TEMPERATURE", "0.55").strip())
    except ValueError:
        temperature = 0.55

    use_image_input = parse_bool(
        args.use_image_input or os.getenv("USE_IMAGE_INPUT_FOR_DIALOGUE", "true"),
        default=True,
    )

    week_dir = resolve_week_dir(args.week_dir)
    summary_path = week_dir / "weekly_forest_summary.json"
    summary = load_json(summary_path, {})
    if not summary:
        raise FileNotFoundError(f"Missing or empty weekly_forest_summary.json: {summary_path}")

    scene_count = len(as_list(summary.get("video_visual_scenes")))
    found_images = sum(
        1
        for scene in as_list(summary.get("video_visual_scenes"))
        if isinstance(scene, dict) and find_scene_image(week_dir, str(scene.get("scene_id", "")))
    )
    effective_image_input = bool(use_image_input and found_images > 0)

    print(f"[INFO] Week dir: {week_dir}")
    print(f"[INFO] Dialogue model: {model}")
    print(f"[INFO] Dialogue temperature: {temperature}")
    print(f"[INFO] USE_IMAGE_INPUT_FOR_DIALOGUE requested: {use_image_input}")
    print(f"[INFO] Scene images found: {found_images}/{scene_count}")
    print(f"[INFO] Effective image input: {effective_image_input}")

    content_parts = build_content_parts(summary, week_dir, effective_image_input)
    data = call_gemini_json(
        parts=content_parts,
        model=model,
        api_key=api_key,
        temperature=temperature,
    )
    # === Core post-processing pipeline ===
    # 1. Rebalance long monologues before adding final closing, so the last scene can also be split if needed.
    data = rebalance_long_speaker_turns(data)

    # 2. Ensure the final scene ends with Tom after possible turn rebalancing.
    data = ensure_final_tom_closing(data)

    # 3. Normalize scene alignment, speaker labels, turn IDs, subtitles, and estimated seconds.
    data = normalize_dialogue(data, summary, week_dir, effective_image_input)

    # 4. Add cross-scene news references after all turns are finalized.
    data = enrich_cross_scene_news_references(data)

    # 5. Apply the existing hard-tone sanitizer once only, after the final structure is stable.
    data = sanitize_tone_phrases(data)

    # 6. Final QC note for very short Tom turns.
    data = ensure_minimum_tom_turns(data)

    json_path = week_dir / "video_dialogue_script.json"
    md_path = week_dir / "video_dialogue_script.md"
    save_json(json_path, data)
    save_text(md_path, build_markdown(data))

    print(f"[OK] Created {json_path}")
    print(f"[OK] Created {md_path}")


if __name__ == "__main__":
    main()
