#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
95 Generate TTS Audio from Video Dialogue Script

Purpose:
- Read video_dialogue_script.json generated by Step 94.
- Generate per-turn Gemini TTS audio for Tom / Miranda.
- Concatenate turn audio into scene-level WAV files and one full-dialogue WAV.
- Do NOT generate video.

Design:
- Single-speaker per request.
- Voice is selected by Python code, not by the model.
- Do not send speaker labels such as "Tom:" or "Miranda:" into the TTS prompt.
- This avoids Gemini accidentally performing multi-speaker dialogue.

Input:
- output/weekly/YYYY-MM-DD/video_dialogue_script.json

Output:
- output/weekly/YYYY-MM-DD/tts_audio/turns/{scene_id}_{turn_id}_{speaker}.wav
- output/weekly/YYYY-MM-DD/tts_audio/scenes/{scene_id}.wav
- output/weekly/YYYY-MM-DD/tts_audio/full_dialogue.wav
- output/weekly/YYYY-MM-DD/tts_audio_manifest.json

Required env:
- GEMINI_API_KEY

Optional env:
- TTS_MODEL, default: gemini-3.1-flash-tts-preview
- TOM_VOICE, default: Puck
- MIRANDA_VOICE, default: Kore
- FORCE_REGENERATE_TTS, default: false
- TTS_TURN_PAUSE_MS, default: 180
- TTS_SCENE_PAUSE_MS, default: 700
- TTS_DRY_RUN, default: false
"""

import argparse
import base64
import json
import os
import re
import socket
import time
import urllib.error
import urllib.parse
import urllib.request
import wave
from pathlib import Path
from typing import Any, Dict, List, Tuple


ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_WEEKLY_DIR = ROOT_DIR / "output" / "weekly"

DEFAULT_TTS_MODEL = "gemini-3.1-flash-tts-preview"
DEFAULT_TOM_VOICE = "Puck"
DEFAULT_MIRANDA_VOICE = "Kore"

AUDIO_RATE = 24000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH = 2


def parse_bool(value: str, default: bool = False) -> bool:
    if value is None:
        return default
    text = str(value).strip().lower()
    if text in {"1", "true", "yes", "y", "on"}:
        return True
    if text in {"0", "false", "no", "n", "off"}:
        return False
    return default


def safe_slug(text: str) -> str:
    text = str(text or "").strip()
    text = re.sub(r"[^A-Za-z0-9_\-]+", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return text or "item"


def find_latest_week_dir() -> Path:
    week_dirs = [p for p in OUTPUT_WEEKLY_DIR.iterdir() if p.is_dir()]
    if not week_dirs:
        raise FileNotFoundError("No weekly output folder found under output/weekly/")
    week_dirs.sort(key=lambda p: p.name, reverse=True)
    return week_dirs[0]


def resolve_week_dir(week_dir_arg: str) -> Path:
    if week_dir_arg:
        week_dir = Path(week_dir_arg)
        if week_dir.exists():
            return week_dir
        candidate = OUTPUT_WEEKLY_DIR / week_dir_arg
        if candidate.exists():
            return candidate
        raise FileNotFoundError(f"Week folder not found: {week_dir_arg}")
    return find_latest_week_dir()


def load_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)


def save_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def write_wave(path: Path, pcm: bytes, rate: int = AUDIO_RATE) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(AUDIO_CHANNELS)
        wf.setsampwidth(AUDIO_SAMPLE_WIDTH)
        wf.setframerate(rate)
        wf.writeframes(pcm)


def read_wave_pcm(path: Path) -> Tuple[bytes, int, int, int]:
    with wave.open(str(path), "rb") as wf:
        channels = wf.getnchannels()
        sample_width = wf.getsampwidth()
        rate = wf.getframerate()
        pcm = wf.readframes(wf.getnframes())
    return pcm, channels, sample_width, rate


def wave_duration_seconds(path: Path) -> float:
    with wave.open(str(path), "rb") as wf:
        return wf.getnframes() / float(wf.getframerate())


def silence_pcm(ms: int, rate: int = AUDIO_RATE) -> bytes:
    frames = int(rate * ms / 1000)
    return b"\x00" * frames * AUDIO_CHANNELS * AUDIO_SAMPLE_WIDTH


def concatenate_wavs(wav_paths: List[Path], out_path: Path, pause_ms: int = 180) -> float:
    pcm_parts: List[bytes] = []
    pause = silence_pcm(pause_ms)

    for idx, path in enumerate(wav_paths):
        if not path.exists():
            continue
        pcm, channels, sample_width, rate = read_wave_pcm(path)
        if channels != AUDIO_CHANNELS or sample_width != AUDIO_SAMPLE_WIDTH or rate != AUDIO_RATE:
            raise ValueError(
                f"Unexpected WAV format for {path}: "
                f"channels={channels}, sample_width={sample_width}, rate={rate}"
            )
        if idx > 0:
            pcm_parts.append(pause)
        pcm_parts.append(pcm)

    combined = b"".join(pcm_parts)
    write_wave(out_path, combined, rate=AUDIO_RATE)
    return wave_duration_seconds(out_path)


def collect_turns(dialogue: Dict[str, Any]) -> List[Dict[str, Any]]:
    turns: List[Dict[str, Any]] = []
    for scene in dialogue.get("scene_dialogues", []) or []:
        if not isinstance(scene, dict):
            continue
        scene_id = str(scene.get("scene_id", "scene"))
        scene_type = str(scene.get("scene_type", ""))
        screen_title = str(scene.get("screen_title", ""))

        for idx, turn in enumerate(scene.get("speaker_turns", []) or [], start=1):
            if not isinstance(turn, dict):
                continue
            speaker = str(turn.get("speaker", "Miranda")).strip()
            if speaker not in {"Tom", "Miranda"}:
                speaker = "Miranda"

            turn_id = str(turn.get("turn_id") or f"{scene_id}_turn_{idx:02d}")
            spoken_text = str(turn.get("spoken_text", "")).strip()
            if not spoken_text:
                continue

            turns.append({
                "scene_id": scene_id,
                "scene_type": scene_type,
                "screen_title": screen_title,
                "turn_id": turn_id,
                "speaker": speaker,
                "spoken_text": spoken_text,
                "subtitle_text": str(turn.get("subtitle_text", "")),
                "speaker_label_text": str(turn.get("speaker_label_text", f"{speaker}")),
                "estimated_seconds": turn.get("estimated_seconds", 0),
                "news_reference": turn.get("news_reference", []),
                "visual_reference": turn.get("visual_reference", ""),
            })
    return turns


def build_tts_prompt(turn: Dict[str, Any]) -> str:
    """
    Build a single-speaker TTS prompt.

    Important:
    - Do not include "Tom:" or "Miranda:" labels in the prompt.
    - Each request contains only one speaker's line.
    - Voice identity is controlled only by voiceName in speechConfig.
    """
    speaker = turn["speaker"]
    text = turn["spoken_text"]

    if speaker == "Tom":
        style = (
            "Read exactly the following Traditional Chinese financial-program host line. "
            "Voice style: male host, warm, clear, steady, curious, professional. "
            "Pace: calm but conversational. "
            "Only read the line itself. Do not read speaker names. "
            "Do not perform multiple characters. Do not add extra words."
        )
    else:
        style = (
            "Read exactly the following Traditional Chinese macro strategist line. "
            "Voice style: female strategist, calm, authoritative, analytical, precise. "
            "Pace: steady and slightly slower than casual conversation. "
            "Only read the line itself. Do not read speaker names. "
            "Do not perform multiple characters. Do not add extra words."
        )

    return f"{style}\n\n{text}"


def extract_audio_bytes(api_response: Dict[str, Any]) -> bytes:
    candidates = api_response.get("candidates") or []
    if not candidates:
        raise RuntimeError(f"Gemini TTS returned no candidates: {api_response}")

    parts = (candidates[0].get("content") or {}).get("parts") or []
    for part in parts:
        inline_data = part.get("inlineData") or part.get("inline_data")
        if not isinstance(inline_data, dict):
            continue
        data = inline_data.get("data")
        if data:
            return base64.b64decode(data)

    raise RuntimeError(f"Gemini TTS response has no inline audio data: {api_response}")


def call_gemini_tts(
    text_prompt: str,
    voice_name: str,
    model: str,
    api_key: str,
    max_retries: int = 4,
) -> bytes:
    endpoint = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        + urllib.parse.quote(model)
        + ":generateContent?key="
        + urllib.parse.quote(api_key)
    )

    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": text_prompt}],
            }
        ],
        "generationConfig": {
            "responseModalities": ["AUDIO"],
            "speechConfig": {
                "voiceConfig": {
                    "prebuiltVoiceConfig": {
                        "voiceName": voice_name,
                    }
                }
            },
        },
    }

    request_body = json.dumps(payload).encode("utf-8")

    for attempt in range(max_retries + 1):
        request = urllib.request.Request(
            endpoint,
            data=request_body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=360) as response:
                raw = response.read().decode("utf-8")
            return extract_audio_bytes(json.loads(raw))

        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            retryable = exc.code in {429, 500, 502, 503, 504}
            if not retryable or attempt >= max_retries:
                raise RuntimeError(f"Gemini TTS HTTPError {exc.code}: {detail}") from exc

            retry_after = exc.headers.get("Retry-After")
            if retry_after and retry_after.isdigit():
                sleep_seconds = int(retry_after)
            else:
                sleep_seconds = min(60, 2 ** attempt * 5)
            print(f"[WARN] Gemini TTS HTTP {exc.code}. Retry in {sleep_seconds}s. Attempt {attempt + 1}/{max_retries}")
            time.sleep(sleep_seconds)

        except (urllib.error.URLError, TimeoutError, socket.timeout) as exc:
            if attempt >= max_retries:
                raise RuntimeError(f"Gemini TTS request failed or timed out: {exc}") from exc
            sleep_seconds = min(60, 2 ** attempt * 5)
            print(f"[WARN] Gemini TTS request error. Retry in {sleep_seconds}s. Attempt {attempt + 1}/{max_retries}: {exc}")
            time.sleep(sleep_seconds)

    raise RuntimeError("Gemini TTS failed after retries.")


def build_scene_audio(
    turns_manifest: List[Dict[str, Any]],
    scenes_dir: Path,
    turn_pause_ms: int,
) -> List[Dict[str, Any]]:
    scene_groups: Dict[str, List[Path]] = {}
    scene_titles: Dict[str, str] = {}

    for item in turns_manifest:
        scene_id = item["scene_id"]
        audio_file = item.get("audio_file", "")
        if not audio_file:
            continue
        path = Path(audio_file)
        if not path.exists():
            continue
        scene_groups.setdefault(scene_id, []).append(path)
        scene_titles.setdefault(scene_id, item.get("screen_title", ""))

    scene_manifest: List[Dict[str, Any]] = []
    for scene_id, paths in scene_groups.items():
        out_path = scenes_dir / f"{scene_id}.wav"
        duration = concatenate_wavs(paths, out_path, pause_ms=turn_pause_ms)
        scene_manifest.append({
            "scene_id": scene_id,
            "screen_title": scene_titles.get(scene_id, ""),
            "audio_file": str(out_path),
            "duration_seconds": round(duration, 2),
            "turn_count": len(paths),
        })

    return scene_manifest


def build_full_audio(
    scene_manifest: List[Dict[str, Any]],
    out_path: Path,
    scene_pause_ms: int,
) -> float:
    scene_paths = [
        Path(item["audio_file"])
        for item in scene_manifest
        if item.get("audio_file") and Path(item["audio_file"]).exists()
    ]
    if not scene_paths:
        return 0.0
    return concatenate_wavs(scene_paths, out_path, pause_ms=scene_pause_ms)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--week-dir", type=str, default="")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key and not args.dry_run:
        raise EnvironmentError("Missing GEMINI_API_KEY.")

    week_dir = resolve_week_dir(args.week_dir)
    dialogue_path = week_dir / "video_dialogue_script.json"
    dialogue = load_json(dialogue_path, {})

    if not dialogue:
        raise FileNotFoundError(f"Missing or empty video_dialogue_script.json: {dialogue_path}")

    tts_model = os.getenv("TTS_MODEL", DEFAULT_TTS_MODEL).strip() or DEFAULT_TTS_MODEL
    tom_voice = os.getenv("TOM_VOICE", DEFAULT_TOM_VOICE).strip() or DEFAULT_TOM_VOICE
    miranda_voice = os.getenv("MIRANDA_VOICE", DEFAULT_MIRANDA_VOICE).strip() or DEFAULT_MIRANDA_VOICE
    force_regenerate = parse_bool(os.getenv("FORCE_REGENERATE_TTS", "false"), default=False)
    env_dry_run = parse_bool(os.getenv("TTS_DRY_RUN", "false"), default=False)
    dry_run = bool(args.dry_run or env_dry_run)
    turn_pause_ms = int(os.getenv("TTS_TURN_PAUSE_MS", "180"))
    scene_pause_ms = int(os.getenv("TTS_SCENE_PAUSE_MS", "700"))

    out_dir = week_dir / "tts_audio"
    turns_dir = out_dir / "turns"
    scenes_dir = out_dir / "scenes"
    turns_dir.mkdir(parents=True, exist_ok=True)
    scenes_dir.mkdir(parents=True, exist_ok=True)

    turns = collect_turns(dialogue)
    if not turns:
        raise ValueError("No speaker_turns found in video_dialogue_script.json.")

    print(f"[INFO] Week dir: {week_dir}")
    print(f"[INFO] TTS model: {tts_model}")
    print(f"[INFO] Tom voice: {tom_voice}")
    print(f"[INFO] Miranda voice: {miranda_voice}")
    print(f"[INFO] Turns: {len(turns)}")
    print(f"[INFO] Dry run: {dry_run}")
    print(f"[INFO] Force regenerate: {force_regenerate}")

    turns_manifest: List[Dict[str, Any]] = []

    for index, turn in enumerate(turns, start=1):
        speaker = turn["speaker"]
        voice = tom_voice if speaker == "Tom" else miranda_voice
        file_stem = f"{safe_slug(turn['scene_id'])}_{safe_slug(turn['turn_id'])}_{speaker}"
        audio_path = turns_dir / f"{file_stem}.wav"

        print(f"[INFO] [{index}/{len(turns)}] {turn['turn_id']} {speaker}")

        if dry_run:
            duration = float(turn.get("estimated_seconds") or 0)
            audio_file = ""
        else:
            if audio_path.exists() and not force_regenerate:
                print(f"[SKIP] Existing audio: {audio_path}")
            else:
                prompt = build_tts_prompt(turn)
                pcm = call_gemini_tts(
                    text_prompt=prompt,
                    voice_name=voice,
                    model=tts_model,
                    api_key=api_key,
                )
                write_wave(audio_path, pcm)

            duration = wave_duration_seconds(audio_path)
            audio_file = str(audio_path)

        turns_manifest.append({
            "index": index,
            "scene_id": turn["scene_id"],
            "scene_type": turn["scene_type"],
            "screen_title": turn["screen_title"],
            "turn_id": turn["turn_id"],
            "speaker": speaker,
            "voice_name": voice,
            "spoken_text": turn["spoken_text"],
            "subtitle_text": turn["subtitle_text"],
            "speaker_label_text": turn["speaker_label_text"],
            "estimated_seconds": turn.get("estimated_seconds", 0),
            "duration_seconds": round(duration, 2),
            "audio_file": audio_file,
            "news_reference": turn.get("news_reference", []),
            "visual_reference": turn.get("visual_reference", ""),
        })

    if dry_run:
        scene_manifest: List[Dict[str, Any]] = []
        full_duration = 0.0
    else:
        scene_manifest = build_scene_audio(
            turns_manifest=turns_manifest,
            scenes_dir=scenes_dir,
            turn_pause_ms=turn_pause_ms,
        )
        full_audio_path = out_dir / "full_dialogue.wav"
        full_duration = build_full_audio(
            scene_manifest=scene_manifest,
            out_path=full_audio_path,
            scene_pause_ms=scene_pause_ms,
        )

    manifest = {
        "meta": {
            "source": "video_dialogue_script.json",
            "purpose": "TTS audio manifest for Step 96 video composition",
            "week_range": (dialogue.get("meta") or {}).get("week_range", ""),
            "tts_model": tts_model,
            "tom_voice": tom_voice,
            "miranda_voice": miranda_voice,
            "dry_run": dry_run,
            "turn_pause_ms": turn_pause_ms,
            "scene_pause_ms": scene_pause_ms,
            "turn_count": len(turns_manifest),
            "scene_count": len(scene_manifest),
            "full_duration_seconds": round(full_duration, 2),
        },
        "input_dialogue_script": str(dialogue_path),
        "output_dir": str(out_dir),
        "turns": turns_manifest,
        "scenes": scene_manifest,
        "full_audio_file": str(out_dir / "full_dialogue.wav") if not dry_run else "",
    }

    manifest_path = week_dir / "tts_audio_manifest.json"
    save_json(manifest_path, manifest)

    print(f"[OK] Created {manifest_path}")
    if not dry_run:
        print(f"[OK] Created {out_dir / 'full_dialogue.wav'}")
        print(f"[INFO] Full duration seconds: {round(full_duration, 2)}")


if __name__ == "__main__":
    main()
